import type { EntityField, FieldType, Project } from '../types'
import { oneLiner } from './ideation'
import { grouped } from './scoping'
import { stripEndPunct } from './text'

export interface GeneratedFile {
  path: string
  content: string
}

export interface Names {
  product: string
  slug: string
  Entity: string
  entity: string
  entities: string
  Entities: string
}

const RESERVED = new Set(['_id', 'id', '__v', 'owner', 'createdAt', 'updatedAt'])
const JS_RESERVED = new Set([
  'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger', 'default', 'delete', 'do', 'else', 'export',
  'extends', 'false', 'finally', 'for', 'function', 'if', 'import', 'in', 'instanceof', 'new', 'null', 'return',
  'super', 'switch', 'this', 'throw', 'true', 'try', 'typeof', 'var', 'void', 'while', 'with', 'yield', 'let', 'static',
])

function wordsOf(s: string): string[] {
  return s
    .normalize('NFKD')
    .replace(/[^\p{L}\p{N}\s_-]/gu, ' ')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(/[\s_-]+/)
    .filter(Boolean)
    .map((w) => w.replace(/[^A-Za-z0-9]/g, ''))
    .filter(Boolean)
}

export function pascalCase(s: string): string {
  return wordsOf(s)
    .map((w) => w[0].toUpperCase() + w.slice(1).toLowerCase())
    .join('')
}

export function camelCase(s: string): string {
  const p = pascalCase(s)
  return p ? p[0].toLowerCase() + p.slice(1) : p
}

export function kebabCase(s: string): string {
  return wordsOf(s)
    .map((w) => w.toLowerCase())
    .join('-')
}

export function pluralize(word: string): string {
  if (/[^aeiou]y$/i.test(word)) return word.slice(0, -1) + 'ies'
  if (/(s|x|z|ch|sh)$/i.test(word)) return word + 'es'
  return word + 's'
}

export function names(project: Project): Names {
  const product = project.ideation.productName.trim() || project.name.replace(/\(demo\)/i, '').trim() || 'My MVP'
  let Entity = pascalCase(project.building.entityName) || 'Item'
  if (/^\d/.test(Entity)) Entity = 'Item' + Entity
  if (Entity === 'User') Entity = 'Profile'
  const entity = Entity[0].toLowerCase() + Entity.slice(1)
  const entities = pluralize(entity)
  return {
    product,
    slug: kebabCase(product) || 'my-mvp',
    Entity,
    entity,
    entities,
    Entities: entities[0].toUpperCase() + entities.slice(1),
  }
}

/** Valid, unique, non-reserved field names. Invalid rows are dropped. */
export function cleanFields(fields: EntityField[]): EntityField[] {
  const seen = new Set<string>()
  const out: EntityField[] = []
  for (const f of fields) {
    let name = camelCase(f.name)
    if (!name) continue
    if (/^\d/.test(name)) name = 'f' + name
    if (RESERVED.has(name) || JS_RESERVED.has(name) || seen.has(name)) continue
    seen.add(name)
    out.push({ ...f, name })
  }
  return out
}

export function fieldsOrDefault(project: Project): EntityField[] {
  const fields = cleanFields(project.building.fields)
  return fields.length ? fields : [{ id: 'default', name: 'title', type: 'String', required: true }]
}

function labelOf(name: string): string {
  const spaced = name.replace(/([a-z0-9])([A-Z])/g, '$1 $2').toLowerCase()
  return spaced[0].toUpperCase() + spaced.slice(1)
}

function schemaLine(f: EntityField): string {
  const parts = [`type: ${f.type}`]
  if (f.required && f.type !== 'Boolean') parts.push('required: true')
  if (f.type === 'String') parts.push('trim: true')
  if (f.type === 'Boolean') parts.push('default: false')
  return `    ${f.name}: { ${parts.join(', ')} },`
}

const INPUT_TYPE: Record<FieldType, string> = { String: 'text', Number: 'number', Boolean: 'checkbox', Date: 'datetime-local' }

export const GENERATED_VERSIONS = {
  express: '^5.2.1',
  mongoose: '^9.11.0',
  bcryptjs: '^3.0.3',
  jsonwebtoken: '^9.0.3',
  cors: '^2.8.6',
  react: '^19.3.0',
  reactDom: '^19.3.0',
  vite: '^8.3.2',
  pluginReact: '^6.1.2',
}

export function generateStarter(project: Project): GeneratedFile[] {
  const n = names(project)
  const fields = fieldsOrDefault(project)
  const v = GENERATED_VERSIONS
  const files: GeneratedFile[] = []
  const add = (path: string, content: string) => files.push({ path, content: content.replace(/^\n/, '') })

  const fieldNames = fields.map((f) => `'${f.name}'`).join(', ')
  const groups = grouped(project.scoping.features)
  const flow = project.scoping.coreFlow
  const outcome = project.scoping.outcome.trim() || stripEndPunct(project.ideation.outcome)

  // ------------------------------------------------------------------ root
  add(
    'README.md',
    `
# ${n.product}

> ${oneLiner(project.ideation).includes('[') ? `MVP starter for ${n.product}.` : oneLiner(project.ideation)}

Generated by **AI Co-Founder** from the scoped MVP. A minimal MERN app: React front end, Express REST API,
MongoDB via Mongoose, and email + password auth with JWT.

## MVP boundary

- **User:** ${stripEndPunct(project.ideation.targetUser) || 'one specific user type'}
- **Core flow:**${flow.length ? '\n' + flow.map((s, i) => `  ${i + 1}. ${s}`).join('\n') : ' _not defined yet_'}
- **Outcome:** ${outcome || '_not defined yet_'}
- **In v1:** ${groups.keep.map((f) => f.name).join(', ') || '_nothing scoped yet_'}
- **Later:** ${groups.later.map((f) => f.name).join(', ') || '—'}
- **Cut:** ${groups.cut.map((f) => f.name).join(', ') || '—'}

## Run it locally

Requirements: Node.js 20.19+ and MongoDB (local, or a free MongoDB Atlas cluster).

\`\`\`bash
# 1. API
cd server
cp .env.example .env        # then edit MONGODB_URI and JWT_SECRET
npm install
npm run dev                 # http://localhost:5000

# 2. Web app (new terminal)
cd client
npm install
npm run dev                 # http://localhost:5173
\`\`\`

## API

| Method | Path | Description |
| --- | --- | --- |
| GET | /api/health | Health check |
| POST | /api/auth/register | Create an account → \`{ token, user }\` |
| POST | /api/auth/login | Log in → \`{ token, user }\` |
| GET | /api/auth/me | Current user (auth) |
| GET | /api/${n.entities} | List your ${n.entities} (auth) |
| POST | /api/${n.entities} | Create a ${n.entity} (auth) |
| GET | /api/${n.entities}/:id | Get one ${n.entity} (auth) |
| PATCH | /api/${n.entities}/:id | Update a ${n.entity} (auth) |
| DELETE | /api/${n.entities}/:id | Delete a ${n.entity} (auth) |

## Data model: \`${n.Entity}\`

| Field | Type | Required |
| --- | --- | --- |
${fields.map((f) => `| ${f.name} | ${f.type} | ${f.required ? 'yes' : 'no'} |`).join('\n')}
| owner | ObjectId → User | yes |

## Deploy

- **Database:** MongoDB Atlas free tier. Copy the connection string into \`MONGODB_URI\`.
- **API:** any Node host (Render, Railway, Fly.io). Set \`MONGODB_URI\`, \`JWT_SECRET\` and \`CLIENT_ORIGIN\`.
- **Web app:** \`npm run build\` in \`client\`, host \`dist/\` on Netlify, Vercel or GitHub Pages, and set \`VITE_API_URL\` to the API URL.
`,
  )

  add(
    '.gitignore',
    `
node_modules/
dist/
.env
`,
  )

  // ---------------------------------------------------------------- server
  add(
    'server/package.json',
    JSON.stringify(
      {
        name: `${n.slug}-server`,
        version: '0.1.0',
        private: true,
        type: 'module',
        scripts: { dev: 'node --watch src/index.js', start: 'node src/index.js' },
        dependencies: {
          bcryptjs: v.bcryptjs,
          cors: v.cors,
          express: v.express,
          jsonwebtoken: v.jsonwebtoken,
          mongoose: v.mongoose,
        },
        engines: { node: '>=20.19' },
      },
      null,
      2,
    ) + '\n',
  )

  add(
    'server/.env.example',
    `
PORT=5000
MONGODB_URI=mongodb://127.0.0.1:27017/${n.slug.replace(/-/g, '_')}
JWT_SECRET=replace-with-a-long-random-string
CLIENT_ORIGIN=http://localhost:5173
`,
  )

  add(
    'server/src/index.js',
    `
import { existsSync } from 'node:fs'
import cors from 'cors'
import express from 'express'
import mongoose from 'mongoose'
import authRoutes from './routes/auth.js'
import ${n.entity}Routes from './routes/${n.entities}.js'

if (existsSync('.env')) process.loadEnvFile('.env')

for (const key of ['MONGODB_URI', 'JWT_SECRET']) {
  if (!process.env[key]) {
    console.error(\`Missing \${key}. Copy .env.example to .env and fill it in.\`)
    process.exit(1)
  }
}

const app = express()
app.use(cors({ origin: process.env.CLIENT_ORIGIN ? process.env.CLIENT_ORIGIN.split(',') : true }))
app.use(express.json())

app.get('/api/health', (_req, res) => res.json({ ok: true }))
app.use('/api/auth', authRoutes)
app.use('/api/${n.entities}', ${n.entity}Routes)

app.use((_req, res) => res.status(404).json({ error: 'Not found' }))

// Express 5 forwards errors thrown in async handlers here.
app.use((err, _req, res, _next) => {
  if (err.name === 'ValidationError' || err.name === 'CastError') {
    return res.status(400).json({ error: err.message })
  }
  console.error(err)
  res.status(500).json({ error: 'Something went wrong' })
})

const port = Number(process.env.PORT) || 5000
await mongoose.connect(process.env.MONGODB_URI)
app.listen(port, () => console.log(\`${n.product} API ready on http://localhost:\${port}\`))
`,
  )

  add(
    'server/src/models/User.js',
    `
import mongoose from 'mongoose'

const userSchema = new mongoose.Schema(
  {
    name: { type: String, required: true, trim: true },
    email: { type: String, required: true, unique: true, lowercase: true, trim: true },
    passwordHash: { type: String, required: true },
  },
  { timestamps: true },
)

export default mongoose.model('User', userSchema)
`,
  )

  add(
    `server/src/models/${n.Entity}.js`,
    `
import mongoose from 'mongoose'

const ${n.entity}Schema = new mongoose.Schema(
  {
    owner: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
${fields.map(schemaLine).join('\n')}
  },
  { timestamps: true },
)

// Every list query filters by owner and sorts by newest first.
${n.entity}Schema.index({ owner: 1, createdAt: -1 })

export default mongoose.model('${n.Entity}', ${n.entity}Schema)
`,
  )

  add(
    'server/src/middleware/auth.js',
    `
import jwt from 'jsonwebtoken'

export function requireAuth(req, res, next) {
  const header = req.headers.authorization ?? ''
  const token = header.startsWith('Bearer ') ? header.slice(7) : null
  if (!token) return res.status(401).json({ error: 'Please log in' })
  try {
    const payload = jwt.verify(token, process.env.JWT_SECRET)
    req.userId = payload.sub
    next()
  } catch {
    res.status(401).json({ error: 'Your session expired. Please log in again.' })
  }
}

export function signToken(userId) {
  return jwt.sign({ sub: String(userId) }, process.env.JWT_SECRET, { expiresIn: '7d' })
}
`,
  )

  add(
    'server/src/routes/auth.js',
    `
import bcrypt from 'bcryptjs'
import { Router } from 'express'
import { requireAuth, signToken } from '../middleware/auth.js'
import User from '../models/User.js'

const router = Router()

const publicUser = (u) => ({ id: u.id, name: u.name, email: u.email })

router.post('/register', async (req, res) => {
  const { name, email, password } = req.body ?? {}
  if (!name || !email || !password) return res.status(400).json({ error: 'Name, email and password are required' })
  if (String(password).length < 8) return res.status(400).json({ error: 'Password must be at least 8 characters' })
  if (await User.exists({ email: String(email).toLowerCase() })) {
    return res.status(409).json({ error: 'An account with this email already exists' })
  }
  const user = await User.create({ name, email, passwordHash: await bcrypt.hash(String(password), 10) })
  res.status(201).json({ token: signToken(user.id), user: publicUser(user) })
})

router.post('/login', async (req, res) => {
  const { email, password } = req.body ?? {}
  const user = email ? await User.findOne({ email: String(email).toLowerCase() }) : null
  if (!user || !(await bcrypt.compare(String(password ?? ''), user.passwordHash))) {
    return res.status(401).json({ error: 'Wrong email or password' })
  }
  res.json({ token: signToken(user.id), user: publicUser(user) })
})

router.get('/me', requireAuth, async (req, res) => {
  const user = await User.findById(req.userId)
  if (!user) return res.status(404).json({ error: 'User not found' })
  res.json({ user: publicUser(user) })
})

export default router
`,
  )

  add(
    `server/src/routes/${n.entities}.js`,
    `
import { Router } from 'express'
import { requireAuth } from '../middleware/auth.js'
import ${n.Entity} from '../models/${n.Entity}.js'

const router = Router()
router.use(requireAuth)

// Only these fields can be set by the client.
const FIELDS = [${fieldNames}]
const pick = (body = {}) => Object.fromEntries(FIELDS.filter((k) => k in body).map((k) => [k, body[k]]))

router.get('/', async (req, res) => {
  const items = await ${n.Entity}.find({ owner: req.userId }).sort({ createdAt: -1 }).limit(200)
  res.json(items)
})

router.post('/', async (req, res) => {
  const item = await ${n.Entity}.create({ ...pick(req.body), owner: req.userId })
  res.status(201).json(item)
})

router.get('/:id', async (req, res) => {
  const item = await ${n.Entity}.findOne({ _id: req.params.id, owner: req.userId })
  if (!item) return res.status(404).json({ error: '${n.Entity} not found' })
  res.json(item)
})

router.patch('/:id', async (req, res) => {
  const item = await ${n.Entity}.findOneAndUpdate({ _id: req.params.id, owner: req.userId }, pick(req.body), {
    new: true,
    runValidators: true,
  })
  if (!item) return res.status(404).json({ error: '${n.Entity} not found' })
  res.json(item)
})

router.delete('/:id', async (req, res) => {
  const result = await ${n.Entity}.deleteOne({ _id: req.params.id, owner: req.userId })
  if (!result.deletedCount) return res.status(404).json({ error: '${n.Entity} not found' })
  res.status(204).end()
})

export default router
`,
  )

  // ---------------------------------------------------------------- client
  add(
    'client/package.json',
    JSON.stringify(
      {
        name: `${n.slug}-client`,
        version: '0.1.0',
        private: true,
        type: 'module',
        scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
        dependencies: { react: v.react, 'react-dom': v.reactDom },
        devDependencies: { '@vitejs/plugin-react': v.pluginReact, vite: v.vite },
      },
      null,
      2,
    ) + '\n',
  )

  add(
    'client/vite.config.js',
    `
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'

export default defineConfig({
  plugins: [react()],
  // In development, /api calls go to the Express server.
  server: { proxy: { '/api': 'http://localhost:5000' } },
})
`,
  )

  add(
    'client/index.html',
    `
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${n.product}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`,
  )

  add(
    'client/src/main.jsx',
    `
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import './styles.css'

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
`,
  )

  add(
    'client/src/api.js',
    `
const BASE = import.meta.env.VITE_API_URL ?? ''

export function getToken() {
  return localStorage.getItem('token')
}

export function setSession(token) {
  if (token) localStorage.setItem('token', token)
  else localStorage.removeItem('token')
}

export async function api(path, { method = 'GET', body } = {}) {
  const res = await fetch(BASE + '/api' + path, {
    method,
    headers: {
      'Content-Type': 'application/json',
      ...(getToken() ? { Authorization: 'Bearer ' + getToken() } : {}),
    },
    body: body ? JSON.stringify(body) : undefined,
  })
  if (res.status === 204) return null
  const data = await res.json().catch(() => ({}))
  if (!res.ok) throw new Error(data.error ?? 'Request failed (' + res.status + ')')
  return data
}
`,
  )

  add(
    'client/src/App.jsx',
    `
import { useEffect, useState } from 'react'
import { api, getToken, setSession } from './api.js'
import AuthPage from './pages/AuthPage.jsx'
import ${n.Entities}Page from './pages/${n.Entities}Page.jsx'

export default function App() {
  const [user, setUser] = useState(null)
  const [checking, setChecking] = useState(Boolean(getToken()))

  useEffect(() => {
    if (!getToken()) return
    api('/auth/me')
      .then((data) => setUser(data.user))
      .catch(() => setSession(null))
      .finally(() => setChecking(false))
  }, [])

  function onAuth({ token, user }) {
    setSession(token)
    setUser(user)
  }

  function logout() {
    setSession(null)
    setUser(null)
  }

  if (checking) return <p className="center">Loading…</p>
  return (
    <div className="app">
      <header className="top">
        <strong>${n.product}</strong>
        {user && (
          <span>
            {user.name} · <button className="link" onClick={logout}>Log out</button>
          </span>
        )}
      </header>
      {user ? <${n.Entities}Page /> : <AuthPage onAuth={onAuth} />}
    </div>
  )
}
`,
  )

  add(
    'client/src/pages/AuthPage.jsx',
    `
import { useState } from 'react'
import { api } from '../api.js'

export default function AuthPage({ onAuth }) {
  const [mode, setMode] = useState('login')
  const [form, setForm] = useState({ name: '', email: '', password: '' })
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)

  const update = (e) => setForm({ ...form, [e.target.name]: e.target.value })

  async function submit(e) {
    e.preventDefault()
    setBusy(true)
    setError('')
    try {
      onAuth(await api('/auth/' + mode, { method: 'POST', body: form }))
    } catch (err) {
      setError(err.message)
    } finally {
      setBusy(false)
    }
  }

  return (
    <form className="card narrow" onSubmit={submit}>
      <h1>{mode === 'login' ? 'Welcome back' : 'Create your account'}</h1>
      {mode === 'register' && (
        <label>
          Name
          <input name="name" value={form.name} onChange={update} required />
        </label>
      )}
      <label>
        Email
        <input name="email" type="email" value={form.email} onChange={update} required />
      </label>
      <label>
        Password
        <input name="password" type="password" minLength={8} value={form.password} onChange={update} required />
      </label>
      {error && <p className="error">{error}</p>}
      <button disabled={busy}>{mode === 'login' ? 'Log in' : 'Sign up'}</button>
      <button type="button" className="link" onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>
        {mode === 'login' ? 'New here? Create an account' : 'Have an account? Log in'}
      </button>
    </form>
  )
}
`,
  )

  const emptyForm = fields.map((f) => `${f.name}: ${f.type === 'Boolean' ? 'false' : "''"}`).join(', ')
  const inputs = fields
    .map((f) =>
      f.type === 'Boolean'
        ? `        <label className="check">
          <input type="checkbox" name="${f.name}" checked={form.${f.name}} onChange={update} />
          ${labelOf(f.name)}
        </label>`
        : `        <label>
          ${labelOf(f.name)}
          <input type="${INPUT_TYPE[f.type]}" name="${f.name}" value={form.${f.name}} onChange={update}${f.required ? ' required' : ''}${f.type === 'Number' ? ' step="any"' : ''} />
        </label>`,
    )
    .join('\n')
  const display = fields
    .map((f) => {
      const val =
        f.type === 'Boolean'
          ? `item.${f.name} ? 'Yes' : 'No'`
          : f.type === 'Date'
            ? `item.${f.name} ? new Date(item.${f.name}).toLocaleString() : '—'`
            : `item.${f.name} ?? '—'`
      return `              <span>
                <small>${labelOf(f.name)}</small> {${val}}
              </span>`
    })
    .join('\n')
  const toPayload = fields
    .map((f) =>
      f.type === 'Number'
        ? `${f.name}: form.${f.name} === '' ? undefined : Number(form.${f.name})`
        : f.type === 'Date'
          ? `${f.name}: form.${f.name} ? new Date(form.${f.name}).toISOString() : undefined`
          : f.type === 'String'
            ? `${f.name}: form.${f.name} || undefined`
            : `${f.name}: form.${f.name}`,
    )
    .join(',\n      ')

  add(
    `client/src/pages/${n.Entities}Page.jsx`,
    `
import { useEffect, useState } from 'react'
import { api } from '../api.js'

const EMPTY = { ${emptyForm} }

export default function ${n.Entities}Page() {
  const [items, setItems] = useState([])
  const [form, setForm] = useState(EMPTY)
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    api('/${n.entities}')
      .then(setItems)
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false))
  }, [])

  function update(e) {
    const { name, type, value, checked } = e.target
    setForm({ ...form, [name]: type === 'checkbox' ? checked : value })
  }

  async function create(e) {
    e.preventDefault()
    setError('')
    const payload = {
      ${toPayload},
    }
    try {
      const item = await api('/${n.entities}', { method: 'POST', body: payload })
      setItems([item, ...items])
      setForm(EMPTY)
    } catch (err) {
      setError(err.message)
    }
  }

  async function remove(id) {
    try {
      await api('/${n.entities}/' + id, { method: 'DELETE' })
      setItems(items.filter((i) => i._id !== id))
    } catch (err) {
      setError(err.message)
    }
  }

  return (
    <main className="grid">
      <form className="card" onSubmit={create}>
        <h2>New ${n.entity}</h2>
${inputs}
        <button>Add ${n.entity}</button>
        {error && <p className="error">{error}</p>}
      </form>
      <section>
        <h2>Your ${n.entities}</h2>
        {loading ? (
          <p>Loading…</p>
        ) : items.length === 0 ? (
          <p className="muted">No ${n.entities} yet. Add your first one.</p>
        ) : (
          <ul className="list">
            {items.map((item) => (
              <li key={item._id} className="card row">
                <div className="fields">
${display}
                </div>
                <button className="link danger" onClick={() => remove(item._id)}>
                  Delete
                </button>
              </li>
            ))}
          </ul>
        )}
      </section>
    </main>
  )
}
`,
  )

  add(
    'client/src/styles.css',
    `
* { box-sizing: border-box; }
body { margin: 0; font-family: system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif; background: #f6f1ea; color: #231d19; }
.app { max-width: 960px; margin: 0 auto; padding: 0 16px 48px; }
.top { display: flex; justify-content: space-between; align-items: center; padding: 18px 0; }
.top strong { font-size: 20px; color: #6b3f22; }
.center { text-align: center; margin-top: 30vh; }
.grid { display: grid; grid-template-columns: minmax(0, 340px) minmax(0, 1fr); gap: 24px; align-items: start; }
@media (max-width: 720px) { .grid { grid-template-columns: 1fr; } }
.card { background: #fffdf9; border: 1px solid #e3d8ca; border-radius: 14px; padding: 18px; }
.narrow { max-width: 380px; margin: 10vh auto 0; }
form.card { display: grid; gap: 12px; }
label { display: grid; gap: 6px; font-size: 14px; font-weight: 600; }
label.check { display: flex; align-items: center; gap: 8px; }
input { height: 40px; padding: 0 12px; border: 1px solid #e3d8ca; border-radius: 10px; font: inherit; background: #fff; }
input[type='checkbox'] { height: auto; }
button { height: 40px; border: 0; border-radius: 10px; background: #6b3f22; color: #f6f1ea; font-weight: 700; cursor: pointer; }
button:disabled { opacity: 0.6; }
button.link { background: none; color: #6b3f22; height: auto; padding: 0; text-decoration: underline; }
button.danger { color: #b4442f; }
h1, h2 { margin: 0 0 4px; }
.list { list-style: none; padding: 0; display: grid; gap: 10px; }
.row { display: flex; justify-content: space-between; gap: 16px; align-items: center; }
.fields { display: flex; flex-wrap: wrap; gap: 8px 18px; }
.fields small { display: block; color: #6f6359; font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; }
.error { color: #b4442f; margin: 0; }
.muted { color: #6f6359; }
`,
  )

  return files
}
